### ISSUE TITLE
landrush_ip_get is called before landrush_ip_install with libvirt provider

### ISSUE THREAD

**Issue by hferentschik** [vagrant-landrush/landrush-ip#5]
```
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: [landrush] setting up machine's DNS to point to our server
==> default: [landrush] network: :forwarded_port, {:guest=>22, :host=>2222,     :host_ip=>"127.0.0.1", :id=>"ssh", :auto_correct=>true, :protocol=>"tcp"}
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

/usr/local/bin/landrush-ip -yaml

Stdout from the command:

Stderr from the command:

bash: line 2: /usr/local/bin/landrush-ip: No such file or directory
```

I believe the issue is, how the [install action](https://github.com/Werelds/landrush-ip/blob/master/lib/landrush-ip/plugin.rb#L53) is registered in relation to Landrush.

**Comment by LalatenduMohanty** [comment]
I faced the same issue while using Vagrant on CentOS with libvirt.

**Comment by Werelds** [comment]
Odd, when I implemented this I could've sworn it worked with Libvirt too. Will test in the coming days unless either of you has an idea for a better hook point for Libvirt?

**Comment by hferentschik** [comment]
@Werelds, did you get a chance to test this?

**Comment by Werelds** [comment]
This'll have been solved to some extent for Libvirt + Landrush users with the new mechanics, but I'm setting up a Linux VM atm in which I'll test libvirt directly. Doing that on OS X is more work than setting up a VM :P
